{
 "title": "Alarms",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "告警总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(severity_1) + sum(severity_2) + sum(severity_3)+ sum(severity_4) + sum(severity_5)  from view_active_alarms_source;"
    }
   ]
  },
  {
   "title": "紧急",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(severity_1) as 紧急 from view_active_alarms_source;"
    }
   ]
  },
  {
   "title": "重要",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(severity_2) as 重要 from view_active_alarms_source;"
    }
   ]
  },
  {
   "title": "次要",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(severity_3) as 次要告警 from view_active_alarms_source;"
    }
   ]
  },
  {
   "title": "警告",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(severity_4) as 警告 from view_active_alarms_source;"
    }
   ]
  },
  {
   "title": "通知",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(severity_5) as 通知 from view_active_alarms_source;"
    }
   ]
  },
  {
   "title": "告警分布",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\r\nsysdate() as time,\r\nTypeName as 资源类型,\r\nsum(severity_1) +\r\nsum(severity_2) +\r\nsum(severity_3) +\r\nsum(severity_4) +\r\nsum(severity_5) 来自\r\nfrom view_active_alarms_source\r\nGROUP BY TypeName;"
    }
   ]
  },
  {
   "title": "告警级别分布",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sysdate() as time, sum(severity_1) as 紧急, sum(severity_2) as 重要, sum(severity_3) as 次要, sum(severity_4) as 警告, sum(severity_5) as 通知  from view_active_alarms_source;"
    }
   ]
  },
  {
   "title": "当前告警源",
   "type": "table",
   "gridPos": { "h": 36, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select CI_Name as 告警源, severity_1 as 紧急, severity_2 as 重要, severity_3 as 次要, severity_4 as 警告, severity_5 as 通知 from view_active_alarms_source;"
    }
   ]
  }
 ]
}