{
 "title": "CMDB",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "资源总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(id)  from CI_Lists;"
    }
   ]
  },
  {
   "title": "资源类型数量",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(typeCode) as 资源类型数量 from CI_Types;"
    }
   ]
  },
  {
   "title": "资源数量占比 (排除Docker Container，资源分组)",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 16, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\nsysdate() as time,\r\ncount(id) as value,\r\ntypeName as metric\r\nFROM CI_Lists WHERE typeCode not IN ('DockerContainer','ZYFZ')\r\nGROUP BY typeName;"
    }
   ]
  },
  {
   "title": "资源数量",
   "type": "table",
   "gridPos": { "h": 27, "w": 4, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "select typeName AS 所有资源类型, count(id) as 资源数量 from CI_Lists group by typeName;"
    }
   ]
  },
  {
   "title": "资源类型编码",
   "type": "table",
   "gridPos": { "h": 27, "w": 4, "x": 4, "y": 4 },
   "targets": [
    {
     "rawSql": "select CI_Type as 资源类型, typeCode as 编码  from CI_Types;"
    }
   ]
  },
  {
   "title": "各类型资源数量对比 (排除Docker Container，资源分组)",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 16, "x": 8, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\r\nsysdate() as time,\r\ncount(id) as value,\r\ntypeName as metric\r\nFROM CI_Lists WHERE typeCode not IN ('DockerContainer','ZYFZ')\r\nGROUP BY typeName;"
    }
   ]
  },
  {
   "title": "资源类型数量",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "select RE_Name as 关系类型, creator as 创建者 from RE_Types;"
    }
   ]
  }
 ]
}