{
 "title": "IOM",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "type": "geomap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select\nlocation as 位置,\nlatitude as 精度,\nlongtitude as 纬度\nfrom GPS;\n"
    }
   ]
  },
  { "title": "Linux监控数据统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Linux系统总数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(monitor_id) as Linux系统总数 FROM view_linux_realtime;"
    }
   ]
  },
  {
   "title": "Linux断开连接",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(monitor_id) as Linux连接失败 FROM IOM_Linux_OS_List where available = \"协议连接失败\";"
    }
   ]
  },
  {
   "title": "Linux紧急告警系统",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(monitor_id) as Linux紧急告警系统 FROM IOM_Linux_OS_List where health = \"紧急\";"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 10, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sysdate() AS TIME, \r\nCONVERT(avg(Memory_Utilization),DECIMAL(5,2)) AS 平均内存使用率, \r\nCONVERT(avg(CPU_Utilization),DECIMAL(5,2)) AS 平均CPU使用率, \r\nCONVERT(avg(Disk_Utilization),DECIMAL(5,2)) AS 平均磁盘使用率 \r\nFROM view_linux_realtime"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT name as 资源,appType as 资源类型, \navailable as 可用性, health as 健康度, \nMemory_Utilization as 内存使用率, \nCPU_Utilization as CPU使用率, \nDisk_Utilization as 磁盘使用率, \nloaded_time as 更新时间\nFROM view_linux_realtime;"
    }
   ]
  },
  { "title": "IOM资源统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "IOM纳管资源数量各类型占比",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\nSYSDATE() AS time,\r\noneCategoryStr AS 类型,\r\ncount(name) AS '-'\r\nfrom IOM_Dev_List\r\nGROUP BY oneCategoryStr;"
    }
   ]
  },
  {
   "title": "IOM纳管各类型资源数量对比 ",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\r\nSYSDATE() AS time,\r\noneCategoryStr AS 类型,\r\ncount(name) AS '-'\r\nfrom IOM_Dev_List\r\nGROUP BY oneCategoryStr;"
    }
   ]
  },
  {
   "title": "IOM资源状态统计",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select name as 资源,\r\nip as IP, oneCategoryStr as 类型, \r\navailable as 可用性, \r\nhealth as 健康度,\r\nloaded_time as 更新时间\r\nfrom IOM_Dev_List;"
    }
   ]
  }
 ]
}